typography_spectrum: 0.017965691396966577
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.41410024277865887
  lightness: 0.7267218630295247
  saturation: 0.3802501866593957
  rhythmicContrast: 0.49303443799726665
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8550996722187847
analytics:
  google: null
  facebook: null
  twitter: null
name: petsrus
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 4 Paws Merch
purpose: []
